In [4]:
import open3d as o3d
import numpy as np
import os

print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud("./pointclouds_mini/003606.pcd")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

Load a ply point cloud, print it, and render it
PointCloud with 44792 points.
[[-60.99494171  38.5594101   -1.25957513]
 [ -3.92985225   2.76194668  -1.34464204]
 [ -4.43209982   3.45029569  -1.12335992]
 ...
 [-44.76479721  39.29914856  -2.08014965]
 [-54.16627884  38.89375305  17.86783218]
 [-46.94709778  37.31665421  10.93432617]]
[Open3D WARNING] GLFW Error: Failed to detect any supported platform
[Open3D WARNING] Failed to initialize GLFW
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.


error: XDG_RUNTIME_DIR is invalid or not set in the environment.
